### ISSUE TITLE
Are data objects only able to play roles in a single context?

### ISSUE THREAD

**Issue by FiGOBLAC** [ciscoheat/dcisniffer#1]
I'm still learning how DCI is supposed to work so I may be misunderstanding the concept here but for some reason I thought the idea was for data objects to be able to play multiple roles across contexts but the Account object can only play the roles available within the MoneyTransfer context.  If I wanted to create another context with possibly similar roles that the Account object could easily fill, I would have to duplicate the Account object in order to use it in another context because the Account object implements roles specific to the MoneyTransfer context. Is this the way its supposed to work?

**Comment by ciscoheat** [comment]
Hello, glad to hear you're interested in DCI! The way it should work is just as you say, data object should play roles in multiple contexts, and in the PHP example you can do that by letting the Account object implement the roles of other contexts. It could result in you having to include every context that it participates in, but it should work fine unless the system is huge.

As an alternative you can skip implementing the interfaces and keep track of them yourself. Since PHP is interpreted and doesn't have the middle ground of duck typing, these are the options, unfortunately. Implementing interfaces at least gives you an early runtime error.

**Comment by FiGOBLAC** [comment]
Thanks for your response. For something as great as DCI I would have thought there would have been a lot of resources but I could only find a few. The way you have things laid out is really elegant and I especially love the RoleMethodContract for type hinting.

> It could result in you having to include every context that it participates in...

I assumed that this might be the case but I was hoping I could avoid inflating an object with so many implementations. I'm working on a project that will allow third party plugins to make use of core objects for role playing within their own contexts, and I'm not sure it would make sense to have an object carry a load of unused implementations.  At some point I would think there will be a few method collisions so I was hoping there was a way to "_unhook from the matrix_"  as Jim Coplien put it in one his talks. I'm not sure if what I'm trying to do is an immature approach but I'm learning as much as I can.
